### ISSUE TITLE
Email body

### ISSUE THREAD

**Issue by davila7** [DemocracyOS/notifier-client#13]
Hi.

Where you create the body of the email to be sent to the user?
I have this code:

notifier.notify(event)
        .to(user.email)
        .withData( { validateUrl: validateUrl } )
        .send(function (err, data) {
          if (err) {
            log('Error when sending notification for event %s to user %j', event, user);
            return callback(err);
          }

          return callback(null, data);
        })

but I don't know where the email html body is created.

Thanks!!

**Comment by gvilarino** [comment]
It's a template in the `DemocracyOS/notifier` repo. This is just a client for that server.

**Comment by gvilarino** [comment]
Check available templates [here](https://github.com/DemocracyOS/notifier/tree/development/source/templates)
